### ISSUE TITLE
negative value

### ISSUE THREAD

**Issue by Ector73** [Petro31/easy-time-jinja#64]
Hi,
i use this code:
```
- sensor:
  - name: giorni_avvio_hassio
    unique_id: Giorni di avvio di HASSIO
    unit_of_measurement: days
    state: >
      {% from 'easy_time.jinja' import count_the_days %}
      {{ count_the_days('sensor.last_boot') }} 
```

![Image](https://github.com/user-attachments/assets/fe420816-0f6a-430e-aece-d866186ea113)
![Image](https://github.com/user-attachments/assets/108c4aae-c216-4fd4-a420-b069740d14ae)

The day count is correct but has a negative value.
How can i solve?

thanks in advance
